repos:
  - repo: local
    hooks:
      # - id: pytest
      #   name: pytest
      #   entry: env PYTHONPATH=. pytest services/ libs/ cleaner/
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   stages: [commit]

      - id: ruff
        name: ruff check
        entry: ruff check --fix --select I services/ libs/ cleaner/
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: ruff format services/ libs/ cleaner/
        language: system
        types: [python]
        pass_filenames: false

      # - id: mypy
      #   name: mypy
      #   entry: mypy services/ libs/ cleaner/ --ignore-missing-imports
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=50000"]
        exclude: "uv.lock"
      - id: detect-private-key
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
