# render.yaml

# If you want session persistence for chat, keep the volume; otherwise omit it.
# volumes:
#   - name: session-data
#     sizeGB: 1

services:
  # 1) Order Service (Free & Ephemeral)
  - type: web
    name: ecom-order
    plan: free
    runtime: docker
    repo: https://github.com/kevon217/ecom-assistant
    branch: master
    dockerfilePath: ./services/order/Dockerfile.render
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: ORDER_DATA_PATH
        value: /app/data/orders_cleaned.csv
      - key: LOG_LEVEL
        value: INFO

  # 2) Product Service (Free & Ephemeral)
  - type: web
    name: ecom-product
    plan: free
    runtime: docker
    repo: https://github.com/kevon217/ecom-assistant
    branch: master
    dockerfilePath: ./services/product/Dockerfile.render
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: PRODUCT_DATA_PATH
        value: /app/data/products_cleaned.csv
      - key: CHROMA_PERSIST_DIR
        value: /app/data/chroma
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
      - key: LOG_LEVEL
        value: INFO

  # 3) Chat Service (waits for its dependencies)
  - type: web
    name: ecom-chat
    plan: free
    runtime: docker
    repo: https://github.com/kevon217/ecom-assistant
    branch: master
    dockerfilePath: ./services/chat/Dockerfile.render
    dockerContext: .
    healthCheckPath: /health
    # Comment out diskMounts below to use ephemeral storage for sessions instead
    # diskMounts:
    #   - volume: session-data
    #     mountPath: /tmp/sessions
    # override the default start to wait on Order & Product

    startCommand: |
      #!/usr/bin/env bash
      set -e
      echo "🌐 Waiting for Order & Product services to be healthy…"
      until curl -sf http://ecom-order:10000/health; do
        echo "⏳ ecom-order not ready, retrying…"
        sleep 5
      done
      until curl -sf http://ecom-product:10000/health; do
        echo "⏳ ecom-product not ready, retrying…"
        sleep 5
      done
      echo "✅ Dependencies up; starting Chat service"
      exec uvicorn chat.app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PORT
        value: 10000
      - key: ORDER_MCP_URL
        value: http://ecom-order:10000/mcp
      - key: PRODUCT_MCP_URL
        value: http://ecom-product:10000/mcp
      - key: OPENAI_API_KEY
        sync: false
      - key: AGENT_MODEL
        value: gpt-4o-mini
      - key: AGENT_TOOL_TIMEOUTS
        value: "30"
      - key: AGENT_TOOL_RETRIES
        value: "3"
      - key: AGENT_MAX_CONCURRENT_TOOLS
        value: "5"
      - key: CHAT_SESSION_TTL
        value: "60"
      - key: CHAT_SESSION_STORE_PATH
        value: "/tmp/sessions"
      - key: CHAT_ALLOWED_ORIGINS
        value: '["*"]'
      - key: LOG_LEVEL
        value: INFO
